#!/bin/bash
while read p; do
	cd "/home/matt/Thesis/Working Sources/SHIVIR/$p"
	for i in $(seq 1 3); do
		ds9 -zoom to fit -zscale -squared $p-Output.fits[$i] -export Output$i.jpeg -exit
	done
done <SHIVIR2.txt


